kcp-dev/infra

- clusters/prow/manifests/prow/01-deck-public.yaml
- clusters/prow/manifests/prow/01-deck.yaml
- clusters/prow/manifests/prow/01-gcsweb-public.yaml
- clusters/prow/manifests/prow/01-gcsweb.yaml
- clusters/prow/manifests/prow/01-hook.yaml
This fixes the wrong target service for the deck-public Ingress and also removes some accidental leftovers from when this might have turned into a Helm chart.
> fix public deck ingress

- clusters/build/hack/ci/deploy.sh
- clusters/prow/hack/ci/deploy.sh
- prow/config.yaml
- prow/jobs/infra/infra-postsubmits.yaml
- prow/jobs/infra/infra-presubmits.yaml
- prow/jobs/logicalcluster/logicalcluster-presubmits.yaml
- prow/plugins.yaml
This PR adds two new postsubmits to automatically deploy the Prow / Build clusters. Prow's configuration (config.yaml, plugin.yaml) are updated by Prow itself, so there doesn't need to be a job to apply those.
> Deploy Prow automatically

- prow/plugins.yaml
The configupdater plugin needs to be enabled explicitly.
> fix missing config_updater plugin for infra repo

- clusters/prow/hack/lib.sh
Without this, the initial jobs would never be updated.
> fix initial job-config ConfigMap not fitting config_updater

- clusters/build/hack/ci/deploy.sh
- clusters/prow/hack/ci/deploy.sh
- hack/lib.sh
Changing the kubeconfig's context doesn't work on read-only volumes mounted from secrets.
> fix context switching in deployment scripts

- clusters/prow/manifests/prow/01-deck-public.yaml
Make sure https://public-prow.kcp.k8c.io/ points to the correct service
> fix deck-public service

- prow/jobs/infra/infra-periodics.yaml
- prow/jobs/infra/infra-presubmits.yaml
The `label-config` configmap is in the prow namespace and the prowjob runs in the default namespace.
Let's avoid using a configmap altogether and derive `labels.yaml` from the cloned infra repo.
> prow/jobs/infra: fix label-sync jobs

- prow/config.yaml
Fixes #16 
This sets up branch protection for all repos in kcp-dev.
/assign @xrstf
> prow/config: add branch protection by default to all repos

- CONTRIBUTING.md
- DCO
- README.md
- SECURITY.md
- code-of-conduct.md
For governance reasons. Except the README, all files are taken from the main kcp repo.
/assign @xrstf
> Add template files

- prow/config.yaml
- prow/jobs/apiextensions-apiserver/apiextensions-apiserver-presubmits.yaml
- prow/jobs/apimachinery/apimachinery-presubmits.yaml
- prow/jobs/awesome-kcp/awesome-kcp-presubmits.yaml
- prow/jobs/client-go/client-go-presubmits.yaml
- prow/jobs/code-generator/code-generator-presubmits.yaml
- prow/jobs/controller-runtime-example/controller-runtime-example-presubmits.yaml
- prow/jobs/controller-runtime/controller-runtime-presubmits.yaml
- prow/jobs/enhancements/enhancements-presubmits.yaml
- prow/jobs/friends/friends-presubmits.yaml
- prow/jobs/helm-charts/helm-charts-presubmits.yaml
- prow/jobs/kcp-dev.github.io/kcp-dev.github.io-presubmits.yaml
- prow/jobs/kcp.io/kcp.io-presubmits.yaml
- prow/jobs/kcp/kcp-presubmits.yaml
This adds all remaining repos to the Prow config, setting up boilerplate verify-yaml jobs for all of them.
Only kcp and logicalcluster repos make use of the release-note plugin, but even that might go away (not sure exactly how changelogs are built in kcp yet).
I also removed the explicit branchprotection rules, as we now have an org-wide setting that seems identical.
part of #25
> add all remaining kcp-dev repositories to prow

- clusters/prow/manifests/prow/01-deck.yaml
Deck needs to be configured with OAuth access to make the tide detail links for each PR work.
> properly configure OAuth for Deck

- .github/workflows/build-image.yaml
- images/build/Dockerfile
This is the _third_ time I'm trying to make Prow merge my PR (previously: #35 and #34).
> This PR is a follow-up to the discussion in Slack regarding the CI job base image.
>
> I've tried my hands at creating a simple version of a build image that ships with Go 1.19.9 and kubectl 1.26.3 and is built via GitHub Actions, since kcp images are currently published as GitHub Packages. I'm very very new to GitHub Actions, so I hope what I built here makes sense. It might not be the way to go for us, so this is open to discussions.
> 🌱  use GitHub Actions to build an image usable for Prow jobs

- .github/workflows/build-image.yaml
`build-args` needs to be passed in a different format. Also see [Actions documentation](https://github.com/docker/build-push-action#customizing) for the proper way to pass a list.
> 🐛  correct format of build args passed to GitHub Actions

- clusters/build/hack/ci/deploy.sh
- clusters/build/manifests/multiarch-deps-installer.yaml
kcp-dev/kcp builds multiarch images, so the build cluster needs to have the necessary dependencies installed.
> add qemu DaemonSet to allow multiarch Docker image building

- prow/config.yaml
xref https://kubernetes.slack.com/archives/C021U8WSAFK/p1686089777445089
This provides a new preset for prowjobs to gain access to the GHCR. Prowjob will need to run in the somewhat protected prow cluster instead of the regular build cluster, as a little extra security. The credentials in this secret can _only_ manage packages and nothing else.
> add preset-ghcr-credentials Prow preset

- prow/jobs/kcp/kcp-postsubmits.yaml
This is the sister PR to https://github.com/kcp-dev/kcp/pull/2976, adding the necessary postsubmit.
Images were previously built for main/release branches and for tags ( https://github.com/kcp-dev/kcp/blob/main/.github/workflows/kcp-image.yaml#L8-L12 ), so I kept this behaviour.
> Add post-kcp-publish-image job

- clusters/build/manifests/machinedeployment-worker.yaml
There is no need to keep 3 large machines running at all times, given the current CI volume. Likewise there should be no scenario at which we need to burst to 30 machines at the same time.
Hence this PR reduces the scaling parameters in order to save money.
> reduce build cluster size to save money

- images/build/Dockerfile
- images/build/README.md
- images/build/env
- images/build/hack/build-image.sh
- images/build/start-docker.sh
This PR includes `kind` and `docker` in the build image and provides a script to start up docker. The README.md included has all the details on how the image should be used, so I don't want to duplicate that information.
We also pre-load a kindest/node image into the image that can be loaded during a Prow job so it doesn't have to be pulled every time.
> 🌱  Include kind and docker in build image

- README.md
- prow/config.yaml
- prow/jobs/kubestellar/kubestellar/kubestellar-presubmits.yaml
- prow/plugins.yaml
This PR converts the Prow config for `kcp-dev/edge-mc` to `kubestellar/kubestellar`.
> migrate edge-mc to kubestellar

- prow/plugins.yaml
Enabling the `transfer-issue` plugin to aid with when we have a new repo for something like tmc and we need to migrate away the issues in kcp-dev/kcp to this repo.
Note: this plugin works only for transferring issues between repos of the same org.
/assign @xrstf
> prow: enable transfer-issue plugin for kcp-dev org

- images/build/Dockerfile
- images/build/env
This updates the build image to Go 1.20.7, Kubernetes 1.28.0 and kind 0.20.0. It's required for the Kubernetes 1.28 rebase (#3003).
> Update build image to Go 1.20, Kubernetes 1.28, kind 0.20

- images/build/Dockerfile
- images/build/env
- images/build/hack/build-image.sh
Helm is used to run presubmit tests in the helm-charts repo.
> add Helm to build image

- images/build/env
This bumps the build image to Go 1.20.9.
> Update to Go 1.20.9

- images/build/Dockerfile
- images/build/README.md
- images/build/env
- images/build/hack/build-image.sh
I would like to add [kubeconform](https://github.com/yannh/kubeconform) to our build image. The reason being that I want this tool to validate our Helm chart after templating it, to make sure that the manifests generated by the chart are not only correct YAML but also semantically correct Kubernetes manifests. Helm currently doesn't check for this as far as I know.
> add kubeconform to build image

- images/build/Dockerfile
- images/build/env
Follow-up to #62. It usually helps to actually copy the binary to where you need it.
> 🐛  correctly copy kubeconform binary into final build image stage

- images/build/env
Some housekeeping before the kcp release, updating to the latest Go 1.20.
/cc @xrstf
> Bump build image to `1.20.13-1`, updating Go to 1.20.13

- images/build/env
Needed for run controller-runtime 0.17.2 tests in https://github.com/kcp-dev/controller-runtime/pull/48.
> Bump to Go 1.21.8

- hack/ci/github-decay-issues.sh
- prow/jobs/kcp-dev/infra/infra-periodics-lifecycle.yaml
These new jobs will let old tickets progressively age and then close them. The plugin itself, for the `/lifecycle` commands, has already been enabled since the beginning.
> define periodics to implement issue lifecycle

- prow/jobs/kcp-dev/generic-controlplane/gcp-postsubmits.yaml
Minor issue in #70, the new postsubmit got added to the wrong repository. It got triggered on a kcp-dev/kcp PR merge and fails: https://public-prow.kcp.k8c.io/view/s3/prow-public-data/logs/post-gcp-publish-image/1791478801046179840.
/cc @xrstf @mjudeikis
> Register gcp postsubmits to correct repository

- images/build/env
- images/build/hack/build-image.sh
Now that https://github.com/kcp-dev/kcp/pull/3140 has been merged, this refreshes the build image to:
1. Use the latest Go 1.22.5.
2. Use Kubernetes 1.30.
3. Update Helm and kubeconform to their latest versions.
4. Build an `arm64` variant of the image so we can run jobs on OCI (#68).
> Update to Go 1.22.5, Kubernetes 1.30 and build arm64 images

- images/build/env
Prepare a go 1.22.7 based build image.
> bump golang to 1.22.7

- images/build/README.md
- prow/config.yaml
- prow/jobs/kcp-dev/kcp-operator/kcp-operator-presubmits.yaml
- prow/plugins.yaml
This PR fixes a stray whitespace in the README for the build image.
Oh, and it also adds the new kcp-operator repo to Prow.
> add kcp-dev/kcp-operator to Prow

- images/build/Dockerfile
- images/build/env
Bumping the Go build image to 1.22.9.
/cc @xrstf
> Update build image to Go 1.22.9, Helm to 3.16.3

- prow/jobs/kcp-dev/kcp-operator/kcp-operator-presubmits.yaml
Looks like we re-used a name from kcp-dev/kcp for the Prowjob here, it should be `pull-kcp-operator-validate-prow-yaml`.
> Update kcp-dev/kcp-operator prow config to use correct job name

- images/build/env
This PR updates the golang toolkit to the latest tag `1.23.4`.
PS: there are other components that could be updated too, please let me know if you'd like to do it all in a single PR or piece-wise.
Fixes: https://github.com/kcp-dev/infra/issues/78
> Updated golang to 1.23.4

- images/build/Dockerfile
- images/build/env
The kcp-operator uses buildah and for the e2e jobs, it needs buildah to be available in our build image.
> add buildah to build image

- images/build/Dockerfile
- images/build/env
- images/build/hack/build-image.sh
Exactly what I predicted would happen, did happen: Since we used the same variable for the version for kubectl and kindest, the kindest.tar inside our build image is completely out-of-sync with kind, and so kind will simply refuse to use it and load its own (1.27.0) whenever a kind cluster is created.
This PR rectifies that by separating the 2 versions and also moving most version info into the Dockerfile. Simply so that we do not need one more env, arg and --build-arg for each new tool we want to add to the Dockerfile.
> separate kubectl and kindest versions in build image, update kind to 0.26.0

- images/build/README.md
- images/build/env
Go 1.23.5 finally released, so here we go.
> Update build image to Go 1.23.5

- clusters/prow/manifests/prow/01-gcsweb-public.yaml
- clusters/prow/manifests/prow/01-gcsweb.yaml
- prow/config.yaml
We tracked down the s3 issues to a simple fact: The gcsweb we use doesn't support S3, it was more recently added.
This PR does the following things:
1. Update to the most recent gcsweb image from k8s/test-infra.
2. Configure the correct flags to use s3 credentials and serve an S3 bucket.
3. Configure the correct gcsweb prefixes into spyglass.
> Update gcsweb configuration to use s3 correctly

- clusters/prow/manifests/machinedeployment-stable.yaml
- clusters/prow/manifests/machinedeployment-worker.yaml
We downgraded our `MachineDeployments` by accident because we forgot at some point to check in our cluster upgrade work into this repository.
> Upgrade MachineDeployments to Kubernetes 1.29.4

- clusters/prow/manifests/prow/01-branchprotector.yaml
We already had configured branch protection rules, but they were never applied. Not anymore!
fixes #91
> add branchprotector cronjob

- prow/config.yaml
We should not only protect `main` branches, but all `release-` branches we have across the org.
/cc @xrstf
> Protect release branches in kcp-dev org

- prow/jobs/kcp-dev/infra/infra-periodics.yaml
kcp-ci-bot doesn't have access to all repositories in kcp-dev, so this PR limits the label_sync job to all repositories that are known to be configured for kcp-ci-bot.
Fixes #96.
> Sync labels only on projects known to be configured for kcp-ci-bot

- iac/oci-prow-worker/.env.example
- iac/oci-prow-worker/.gitignore
- iac/oci-prow-worker/.terraform.lock.hcl
- iac/oci-prow-worker/Makefile
- iac/oci-prow-worker/README.md
- iac/oci-prow-worker/cluster.tf
- iac/oci-prow-worker/network.tf
- iac/oci-prow-worker/outputs.tf
- iac/oci-prow-worker/provider.tf
- iac/oci-prow-worker/terraform.tf
- iac/oci-prow-worker/variables.tf
This PR adds OpenTofu files to maintain our Oracle Cloud prow cluster. For now, I'm not adding automation for it, but we should probably do that as next step.
This PR does the following:
- Set up networking on OCI.
- Create a `oci-prow-worker` OKE cluster. 
- Add a three node node pool with 8 CPUs / 32GB RAM per node.
The SSH key is a key I specifically generated to be shared, so please let me know if you need it.
I'd like to merge this code for now and iterate on it, eventually moving automation to the prow control plane cluster (?).
> Add IaC module for Oracle Cloud prow cluster

- prow/jobs/kcp-dev/infra/infra-periodics.yaml
`--orgs` and `--only` conflicts. Only one should be set.
/cc @xrstf
> Don't set --orgs on label-sync job

- prow/jobs/kcp-dev/kcp/kcp-presubmits-oci.yaml
This is a temporary presubmit job so we can start running jobs on OCI.
/cc @xrstf
> Add presubmit job to kcp-dev/kcp to test OCI worker cluster

- prow/config.yaml
Our oci-prow-worker cluster doesn't have a docker registry mirror, so jobs cannot start there. This makes the environment variable optional.
/cc @xrstf
> Make docker registry environment variable in Prow optional

- prow/config.yaml
Not all of our repositories are managed by prow (yet). This replaces the blanket configuration for github.com/kcp-dev with a list of repositories that is already using prow and thus, can be managed by prow properly (e.g. do the DCO check).
/cc @xrstf
> Only protect branches of repositories managed by prow

- prow/config.yaml
- prow/labels.yaml
- prow/plugins.yaml
This PR is towards https://github.com/kcp-dev/kcp/issues/3351, making `kind/` labels mandatory on our main repositories.
Before this can be merged, all repositories should have their templates updated and #96 has to be fixed.
/hold
> Configure requirement for kind labels to be on PRs

- prow/config.yaml
The branchprotector job is failing because of two reasons:
1. I added a typo in #107.
2. There are several kubestellar repositories that the bot does not appear to have access to, and thus branch protection is failing.
Since KubeStellar is migrating off the shared Prow instance, I'm removing kubestellar from the configuration to unblock the job succeeding.
> Fix typo in kcp-dev branch protection, remove kubestellar

- prow/config.yaml
A follow up to #108, apparently I added another typo that went unnoticed.
> Fix repository name for kcp-dev/apimachinery branch protection

- prow/config.yaml
As a follow-up to previous PRs, this creates additional branch protection for branches with the `kcp-` prefix, which we are using or about to use for the following repositories:
- kcp-dev/kubernetes
- kcp-dev/code-generator
- kcp-dev/apimachinery
- kcp-dev/client-go
> Configure branch protection for "kcp-" branches on some repositories

- iac/oci-prow-worker/.terraform.lock.hcl
- iac/oci-prow-worker/README.md
- iac/oci-prow-worker/addons.tf
- iac/oci-prow-worker/cluster.tf
- iac/oci-prow-worker/network.tf
- iac/oci-prow-worker/variables.tf
This commits changes I made to get the OCI prow cluster functional and into a good state. Unfortunately some things were done by hand, so things are a little messy, but this still applies so that's what's important.
* Create boot volumes with 200GB
* Update security lists
* Use hand-crafted route table
* Upgrade cluster to enhanced
* Install cluster-autoscaler
> Several updates to the OCI prow cluster

- prow/jobs/kcp-dev/api-syncagent/api-syncagent-postsubmits.yaml
The in-repository job uses buildah 1.38.0, but the postsubmit uses 1.30.0:
https://github.com/kcp-dev/api-syncagent/blob/3c8f5f0b4dadc695195d8815f1cedec2229b20b6/.prow.yaml#L57
Let's fix that and align the two versions.
> kcp-dev/api-syncagent: use same buildah version as presubmit job

- prow/plugins.yaml
I would like to propose that we start tracking PRs merged into `main` via GitHub milestones. Doing this mid-release-cycle obviously means it will be an incomplete list, but starting from the next minor release we could have this information.
> kcp-dev/kcp: apply v0.28.0 milestone to merges into main

- images/build/go-1.23/env
- images/build/go-1.24/env
New Go releases contain several CVE fixes.
> bump build image to Go 1.23.10, 1.24.4

- images/build/go-1.23/env
- images/build/go-1.24/Dockerfile
- images/build/go-1.24/env
To prepare the next release cycle, this bumps our build images. Particularly 1.24 gets a bunch of updates all around so we can bump kcp's `main` branch to it.
> Update to Go 1.24.5 and 1.23.11

- prow/config.yaml
- prow/jobs/kcp-dev/infra/infra-periodics.yaml
- prow/jobs/kcp-dev/publishing-bot/publishing-bot-presubmits.yaml
This PR is supposed to register [`kcp-dev/publishing-bot`](https://github.com/kcp-dev/publishing-bot) with Prow so that we have CI in that repo. Jobs will be added later.
/assign @xrstf
> Register kcp-dev/publishing-bot with Prow

- images/build/go-1.24/env
- images/build/go-1.25/env
New Go versions with a long list of security fixes. Worth updating. See https://groups.google.com/d/msgid/golang-announce/459c470d.BAAAB6Txh8AAAAAAAAAAA-p9MGAAAYKKSQYAAAAAADE8OwBo5WD-%40mailjet.com for the full details.
> Update build images to Go 1.24.8 and 1.25.2

- prow/config.yaml
This is so that no merges happen in monorepo'ed repos like client-go or apimachinery.
> set blocker_label in Prow
